### ISSUE TITLE
Phrases should handle the mention being at the end

### ISSUE THREAD

**Issue by pas256** [cloudnative/mercator#2]
When I do

    Help me @pasdevbot

The `Event.get_clean_phrase` method strips out the entire message. Ideally, it should keep `Help me` and return that.

Not sure what to do if the mention is in the middle, or when that would be appropriate.

**Comment by garnaat** [comment]
This got fixed in https://github.com/cloudnative/mercator/commit/dfa078288a5cd3b7186f1a4cad7aff01292e026d

It should find the mention anywhere in the message and leave the rest of the words as they were.
